### ISSUE TITLE
Why I can not compile the .tex file with xelatex successfully？

### ISSUE THREAD

**Issue by kbawyg** [Khaos/DLUTThesis#1]
I encounter the following errors when compiling the .tex file with xelatex. I use the texmaker as the latex editor.
!Latex Error:Unknown option 'fontset = adobe' for package 'ctex'.
!Latex Error:Unknown option 'scheme = Chinsee' for package 'ctex'.
!Latex Error:Unknown option 'fontset = zihao=-4' for package 'ctex'.
!Undefined control sequence. \CJKaddEncHook
!Latex Error:Option clash for package color.
!Undefined control sequence. \xeCJKsetup.
!Undefined control sequence. \ctexset.

**Comment by Khaos** [comment]
You probably need to update your `ctex` package.
