### ISSUE TITLE
tikz external library: change mode to `convert with system call`

### ISSUE THREAD

**Issue by muzimuzhi** [Khaos/DLUTThesis#2]
模板中使用了 tikz external library，并设置了 `mode=list and make`
https://github.com/Khaos/DLUTThesis/blob/04d4c681465d02469a28a1f7dcdf4741de79c09c/dlutthesis.cls#L892
https://github.com/Khaos/DLUTThesis/blob/04d4c681465d02469a28a1f7dcdf4741de79c09c/dlutthesis.cls#L919

根据 tikz 文档 Sec. 52.4.4，`mode=list and make` 的作用是生成 makefile，以支持多线程。
![image](https://user-images.githubusercontent.com/6376638/55290171-42dda300-5402-11e9-9111-55f40e9c61a9.png)

考虑到
 * 模板的用户可能大多使用 windows 系统，而 windows（暂不考虑 WSL 子系统）不支持 makefile
 * 当前的 README 里并没有提到需要 `make xxx.makefile` 这一步

于是，不知情的使用者，就会在编译模板的示例文档时，遇到错误
```
! Package tikz Warning: Some images are not up-to-date and need to be generated
```
这会增加模板用户的困惑。

建议删除对 external mode 的两处改动，恢复默认设置 `mode=convert with system call`。

**Comment by Khaos** [comment]
未来更新可以考虑将key `mode` 作为可设定选项。暂时可以按照你的建议来修改，麻烦帮忙在相应处做出修改并更新一下README，做个pull request，谢谢。

**Comment by muzimuzhi** [comment]
### 信息更新

重新阅读后，我发现 [README/pgftikz](https://github.com/Khaos/DLUTThesis#pgftikz) 的第 3 和第 4 点已经提到了如何单独 tikz 图形。我之前说的
> 当前的 README 里并没有提到需要 make xxx.makefile 这一步

是错误的。

所以
 - 当前，按照使用说明来编译模板，能正常更新 tikz 图形，无 latex 编译错误地生成 PDF
 - 对「修改 tikz external mode」的考量，就退让到考虑
    - 用户真实使用模板时，是否会用到 external tikz file 的功能
    - 当前的 external tikz file 的使用方式，对用户来说是否较为麻烦

### 我的建议

理想情况下，用户在使用模板时，应当通读使用文档，如此就不会遇到我在本 issue 里提到的（我在 latex qq 群里遇到的用户提出的）问题。结合你的回复，从便利用户的角度，我建议
 - 为 `\dlutset` 增加选项 `pgf/externalmode = <mode>`，默认不设置，用户可通过 `pgf/externalmode = list and make` 全局修改 external mode
 - 在命令 `\@dlut@pgf@externalexpensivetrue` 和 `\@dlut@pgf@externalmainfile@set` 内部，删除对 tikz external mode 的设置，即，使用默认设置 `mode = convert with system call`
 - 修改 REAMDE 以适应上述修改

### 小结

在信息更新后，如果 @Khaos 你仍然同意我的建议，我可以提交相应的、合并到 master 分支的 pr。然后由你把关于 REAMDE 的修改，合并到 gh-pages 分支。

**Comment by Khaos** [comment]
同意修改，麻烦提交PR

**Comment by muzimuzhi** [comment]
closed by https://github.com/Khaos/DLUTThesis/commit/df2f85f76d1dd37a0c22cd94ff78d7bed700985f
