### ISSUE TITLE
pdf偶数页为空白

### ISSUE THREAD

**Issue by zzphd** [Khaos/DLUTThesis#4]
环境:
window10+vscode+xelatex+texlive

问题:
对DULTThesis.tex进行编译, 第一个问题是
Figs/Src/IP.tikz 文件的导致编译出错, 所以直接注释了下面的语句后,该问题不再出现:
![image](https://user-images.githubusercontent.com/9635433/75103060-5d2ef980-5630-11ea-94a0-9b03574229d5.png)
之后编译通过, 但生成的pdf中第2,4,6,8,10,12,14页均为空白,其余正常

**Comment by Khaos** [comment]
怀疑是TeXLive版本或包的版本问题，需要参看log查找问题

**Comment by zzphd** [comment]
[DLUTThesis.log](https://github.com/Khaos/DLUTThesis/files/4265251/DLUTThesis.log)
这是文件目录的日志文件, 
此外,我还有一个改动是删除了原文件头部的魔法配置选项,,否则也无法编译.

**Comment by Khaos** [comment]
提供信息有限，系统版本，运行命令及参数未知。初步怀疑与文档类无关，怀疑是字体问题。Close issue
